# Generated by Django 3.2 on 2021-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=60, verbose_name='vorname')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='nachname')),
                ('anstellungsart', models.CharField(blank=True, max_length=60, verbose_name='anstellungsart')),
                ('standort', models.CharField(blank=True, max_length=60, verbose_name='standort')),
                ('team', models.CharField(blank=True, max_length=60, verbose_name='team')),
                ('position', models.CharField(blank=True, max_length=60, verbose_name='position')),
            ],
        ),
    ]
