# Generated by Django 3.2 on 2021-04-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_vorgesetzter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='nachname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='vorname',
        ),
    ]
