# Generated by Django 3.2 on 2021-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vorgesetzter',
            field=models.CharField(blank=True, default='jimmy', max_length=60, verbose_name='vorgesetzter'),
            preserve_default=False,
        ),
    ]
